/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SettingsLayoutRouteRouteImport } from './routes/_settingsLayout/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsPasswordRouteImport } from './routes/settings_/password'
import { Route as SettingsLayoutSettingsIndexRouteImport } from './routes/_settingsLayout/settings/index'
import { Route as SettingsLayoutSettingsProfileRouteImport } from './routes/_settingsLayout/settings/profile'
import { Route as SettingsLayoutSettingsPaymentsRouteImport } from './routes/_settingsLayout/settings/payments'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsLayoutRouteRoute = SettingsLayoutRouteRouteImport.update({
  id: '/_settingsLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPasswordRoute = SettingsPasswordRouteImport.update({
  id: '/settings_/password',
  path: '/settings/password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsLayoutSettingsIndexRoute =
  SettingsLayoutSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => SettingsLayoutRouteRoute,
  } as any)
const SettingsLayoutSettingsProfileRoute =
  SettingsLayoutSettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => SettingsLayoutRouteRoute,
  } as any)
const SettingsLayoutSettingsPaymentsRoute =
  SettingsLayoutSettingsPaymentsRouteImport.update({
    id: '/settings/payments',
    path: '/settings/payments',
    getParentRoute: () => SettingsLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/settings/password': typeof SettingsPasswordRoute
  '/settings/payments': typeof SettingsLayoutSettingsPaymentsRoute
  '/settings/profile': typeof SettingsLayoutSettingsProfileRoute
  '/settings': typeof SettingsLayoutSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/settings/password': typeof SettingsPasswordRoute
  '/settings/payments': typeof SettingsLayoutSettingsPaymentsRoute
  '/settings/profile': typeof SettingsLayoutSettingsProfileRoute
  '/settings': typeof SettingsLayoutSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_settingsLayout': typeof SettingsLayoutRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/settings_/password': typeof SettingsPasswordRoute
  '/_settingsLayout/settings/payments': typeof SettingsLayoutSettingsPaymentsRoute
  '/_settingsLayout/settings/profile': typeof SettingsLayoutSettingsProfileRoute
  '/_settingsLayout/settings/': typeof SettingsLayoutSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/settings/password'
    | '/settings/payments'
    | '/settings/profile'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/settings/password'
    | '/settings/payments'
    | '/settings/profile'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_settingsLayout'
    | '/about'
    | '/settings_/password'
    | '/_settingsLayout/settings/payments'
    | '/_settingsLayout/settings/profile'
    | '/_settingsLayout/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsLayoutRouteRoute: typeof SettingsLayoutRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  SettingsPasswordRoute: typeof SettingsPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_settingsLayout': {
      id: '/_settingsLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SettingsLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/password': {
      id: '/settings_/password'
      path: '/settings/password'
      fullPath: '/settings/password'
      preLoaderRoute: typeof SettingsPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_settingsLayout/settings/': {
      id: '/_settingsLayout/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsLayoutSettingsIndexRouteImport
      parentRoute: typeof SettingsLayoutRouteRoute
    }
    '/_settingsLayout/settings/profile': {
      id: '/_settingsLayout/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsLayoutSettingsProfileRouteImport
      parentRoute: typeof SettingsLayoutRouteRoute
    }
    '/_settingsLayout/settings/payments': {
      id: '/_settingsLayout/settings/payments'
      path: '/settings/payments'
      fullPath: '/settings/payments'
      preLoaderRoute: typeof SettingsLayoutSettingsPaymentsRouteImport
      parentRoute: typeof SettingsLayoutRouteRoute
    }
  }
}

interface SettingsLayoutRouteRouteChildren {
  SettingsLayoutSettingsPaymentsRoute: typeof SettingsLayoutSettingsPaymentsRoute
  SettingsLayoutSettingsProfileRoute: typeof SettingsLayoutSettingsProfileRoute
  SettingsLayoutSettingsIndexRoute: typeof SettingsLayoutSettingsIndexRoute
}

const SettingsLayoutRouteRouteChildren: SettingsLayoutRouteRouteChildren = {
  SettingsLayoutSettingsPaymentsRoute: SettingsLayoutSettingsPaymentsRoute,
  SettingsLayoutSettingsProfileRoute: SettingsLayoutSettingsProfileRoute,
  SettingsLayoutSettingsIndexRoute: SettingsLayoutSettingsIndexRoute,
}

const SettingsLayoutRouteRouteWithChildren =
  SettingsLayoutRouteRoute._addFileChildren(SettingsLayoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsLayoutRouteRoute: SettingsLayoutRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  SettingsPasswordRoute: SettingsPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
