/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SettingsLayoutRouteImport } from './routes/_settingsLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as PostsIndexRouteImport } from './routes/posts.index'
import { Route as PostsPostIdRouteImport } from './routes/posts.$postId'
import { Route as FileSplatRouteImport } from './routes/file.$'
import { Route as SettingsLayoutSettingsRouteImport } from './routes/_settingsLayout.settings'
import { Route as Char123LocaleChar125ArchiveChar123YearChar125RouteImport } from './routes/{-$locale}.archive.{-$year}'
import { Route as PostsPostIdEditRouteImport } from './routes/posts_.$postId.edit'
import { Route as FileFileChar123fileIdChar125SplatRouteImport } from './routes/file.file-{$fileId}.$'
import { Route as SettingsLayoutSettingsPasswordRouteImport } from './routes/_settingsLayout.settings_.password'
import { Route as SettingsLayoutSettingsProfileRouteImport } from './routes/_settingsLayout.settings.profile'
import { Route as SettingsLayoutSettingsPaymentsRouteImport } from './routes/_settingsLayout.settings.payments'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsLayoutRoute = SettingsLayoutRouteImport.update({
  id: '/_settingsLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const FileSplatRoute = FileSplatRouteImport.update({
  id: '/file/$',
  path: '/file/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsLayoutSettingsRoute = SettingsLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SettingsLayoutRoute,
} as any)
const Char123LocaleChar125ArchiveChar123YearChar125Route =
  Char123LocaleChar125ArchiveChar123YearChar125RouteImport.update({
    id: '/{-$locale}/archive/{-$year}',
    path: '/{-$locale}/archive/{-$year}',
    getParentRoute: () => rootRouteImport,
  } as any)
const PostsPostIdEditRoute = PostsPostIdEditRouteImport.update({
  id: '/posts_/$postId/edit',
  path: '/posts/$postId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const FileFileChar123fileIdChar125SplatRoute =
  FileFileChar123fileIdChar125SplatRouteImport.update({
    id: '/file/file-{$fileId}/$',
    path: '/file/file-{$fileId}/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsLayoutSettingsPasswordRoute =
  SettingsLayoutSettingsPasswordRouteImport.update({
    id: '/settings_/password',
    path: '/settings/password',
    getParentRoute: () => SettingsLayoutRoute,
  } as any)
const SettingsLayoutSettingsProfileRoute =
  SettingsLayoutSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => SettingsLayoutSettingsRoute,
  } as any)
const SettingsLayoutSettingsPaymentsRoute =
  SettingsLayoutSettingsPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => SettingsLayoutSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/settings': typeof SettingsLayoutSettingsRouteWithChildren
  '/file/$': typeof FileSplatRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts': typeof PostsIndexRoute
  '/products': typeof ProductsIndexRoute
  '/settings/payments': typeof SettingsLayoutSettingsPaymentsRoute
  '/settings/profile': typeof SettingsLayoutSettingsProfileRoute
  '/settings/password': typeof SettingsLayoutSettingsPasswordRoute
  '/file/file-{$fileId}/$': typeof FileFileChar123fileIdChar125SplatRoute
  '/posts/$postId/edit': typeof PostsPostIdEditRoute
  '/{-$locale}/archive/{-$year}': typeof Char123LocaleChar125ArchiveChar123YearChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/settings': typeof SettingsLayoutSettingsRouteWithChildren
  '/file/$': typeof FileSplatRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts': typeof PostsIndexRoute
  '/products': typeof ProductsIndexRoute
  '/settings/payments': typeof SettingsLayoutSettingsPaymentsRoute
  '/settings/profile': typeof SettingsLayoutSettingsProfileRoute
  '/settings/password': typeof SettingsLayoutSettingsPasswordRoute
  '/file/file-{$fileId}/$': typeof FileFileChar123fileIdChar125SplatRoute
  '/posts/$postId/edit': typeof PostsPostIdEditRoute
  '/{-$locale}/archive/{-$year}': typeof Char123LocaleChar125ArchiveChar123YearChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_settingsLayout': typeof SettingsLayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/_settingsLayout/settings': typeof SettingsLayoutSettingsRouteWithChildren
  '/file/$': typeof FileSplatRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts/': typeof PostsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/_settingsLayout/settings/payments': typeof SettingsLayoutSettingsPaymentsRoute
  '/_settingsLayout/settings/profile': typeof SettingsLayoutSettingsProfileRoute
  '/_settingsLayout/settings_/password': typeof SettingsLayoutSettingsPasswordRoute
  '/file/file-{$fileId}/$': typeof FileFileChar123fileIdChar125SplatRoute
  '/posts_/$postId/edit': typeof PostsPostIdEditRoute
  '/{-$locale}/archive/{-$year}': typeof Char123LocaleChar125ArchiveChar123YearChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/settings'
    | '/file/$'
    | '/posts/$postId'
    | '/posts'
    | '/products'
    | '/settings/payments'
    | '/settings/profile'
    | '/settings/password'
    | '/file/file-{$fileId}/$'
    | '/posts/$postId/edit'
    | '/{-$locale}/archive/{-$year}'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/settings'
    | '/file/$'
    | '/posts/$postId'
    | '/posts'
    | '/products'
    | '/settings/payments'
    | '/settings/profile'
    | '/settings/password'
    | '/file/file-{$fileId}/$'
    | '/posts/$postId/edit'
    | '/{-$locale}/archive/{-$year}'
  id:
    | '__root__'
    | '/'
    | '/_settingsLayout'
    | '/about'
    | '/_settingsLayout/settings'
    | '/file/$'
    | '/posts/$postId'
    | '/posts/'
    | '/products/'
    | '/_settingsLayout/settings/payments'
    | '/_settingsLayout/settings/profile'
    | '/_settingsLayout/settings_/password'
    | '/file/file-{$fileId}/$'
    | '/posts_/$postId/edit'
    | '/{-$locale}/archive/{-$year}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsLayoutRoute: typeof SettingsLayoutRouteWithChildren
  AboutRoute: typeof AboutRoute
  FileSplatRoute: typeof FileSplatRoute
  PostsPostIdRoute: typeof PostsPostIdRoute
  PostsIndexRoute: typeof PostsIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  FileFileChar123fileIdChar125SplatRoute: typeof FileFileChar123fileIdChar125SplatRoute
  PostsPostIdEditRoute: typeof PostsPostIdEditRoute
  Char123LocaleChar125ArchiveChar123YearChar125Route: typeof Char123LocaleChar125ArchiveChar123YearChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_settingsLayout': {
      id: '/_settingsLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SettingsLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/file/$': {
      id: '/file/$'
      path: '/file/$'
      fullPath: '/file/$'
      preLoaderRoute: typeof FileSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_settingsLayout/settings': {
      id: '/_settingsLayout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsLayoutSettingsRouteImport
      parentRoute: typeof SettingsLayoutRoute
    }
    '/{-$locale}/archive/{-$year}': {
      id: '/{-$locale}/archive/{-$year}'
      path: '/{-$locale}/archive/{-$year}'
      fullPath: '/{-$locale}/archive/{-$year}'
      preLoaderRoute: typeof Char123LocaleChar125ArchiveChar123YearChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts_/$postId/edit': {
      id: '/posts_/$postId/edit'
      path: '/posts/$postId/edit'
      fullPath: '/posts/$postId/edit'
      preLoaderRoute: typeof PostsPostIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/file/file-{$fileId}/$': {
      id: '/file/file-{$fileId}/$'
      path: '/file/file-{$fileId}/$'
      fullPath: '/file/file-{$fileId}/$'
      preLoaderRoute: typeof FileFileChar123fileIdChar125SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_settingsLayout/settings_/password': {
      id: '/_settingsLayout/settings_/password'
      path: '/settings/password'
      fullPath: '/settings/password'
      preLoaderRoute: typeof SettingsLayoutSettingsPasswordRouteImport
      parentRoute: typeof SettingsLayoutRoute
    }
    '/_settingsLayout/settings/profile': {
      id: '/_settingsLayout/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsLayoutSettingsProfileRouteImport
      parentRoute: typeof SettingsLayoutSettingsRoute
    }
    '/_settingsLayout/settings/payments': {
      id: '/_settingsLayout/settings/payments'
      path: '/payments'
      fullPath: '/settings/payments'
      preLoaderRoute: typeof SettingsLayoutSettingsPaymentsRouteImport
      parentRoute: typeof SettingsLayoutSettingsRoute
    }
  }
}

interface SettingsLayoutSettingsRouteChildren {
  SettingsLayoutSettingsPaymentsRoute: typeof SettingsLayoutSettingsPaymentsRoute
  SettingsLayoutSettingsProfileRoute: typeof SettingsLayoutSettingsProfileRoute
}

const SettingsLayoutSettingsRouteChildren: SettingsLayoutSettingsRouteChildren =
  {
    SettingsLayoutSettingsPaymentsRoute: SettingsLayoutSettingsPaymentsRoute,
    SettingsLayoutSettingsProfileRoute: SettingsLayoutSettingsProfileRoute,
  }

const SettingsLayoutSettingsRouteWithChildren =
  SettingsLayoutSettingsRoute._addFileChildren(
    SettingsLayoutSettingsRouteChildren,
  )

interface SettingsLayoutRouteChildren {
  SettingsLayoutSettingsRoute: typeof SettingsLayoutSettingsRouteWithChildren
  SettingsLayoutSettingsPasswordRoute: typeof SettingsLayoutSettingsPasswordRoute
}

const SettingsLayoutRouteChildren: SettingsLayoutRouteChildren = {
  SettingsLayoutSettingsRoute: SettingsLayoutSettingsRouteWithChildren,
  SettingsLayoutSettingsPasswordRoute: SettingsLayoutSettingsPasswordRoute,
}

const SettingsLayoutRouteWithChildren = SettingsLayoutRoute._addFileChildren(
  SettingsLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsLayoutRoute: SettingsLayoutRouteWithChildren,
  AboutRoute: AboutRoute,
  FileSplatRoute: FileSplatRoute,
  PostsPostIdRoute: PostsPostIdRoute,
  PostsIndexRoute: PostsIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  FileFileChar123fileIdChar125SplatRoute:
    FileFileChar123fileIdChar125SplatRoute,
  PostsPostIdEditRoute: PostsPostIdEditRoute,
  Char123LocaleChar125ArchiveChar123YearChar125Route:
    Char123LocaleChar125ArchiveChar123YearChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
